# Generated by Django 5.1.6 on 2025-03-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up',
            old_name='fullname',
            new_name='name',
        ),
    ]
